// Generated by CoffeeScript 1.7.1

/* ! CopyRight: binnng http://github.com/binnng/slip.js, Licensed under: MIT */
(function(win, doc) {
  var CSS_PREFIX_MAP, DOWN, LEFT, MAX_OPP_ALLOW_DISTANCE, MIN_ALLOW_DISTANCE, RIGHT, Slip, UP, X, XY, Y, noop, setTranslate, slip;
  MIN_ALLOW_DISTANCE = 10;
  MAX_OPP_ALLOW_DISTANCE = 40;
  CSS_PREFIX_MAP = ["webkit", "moz", "ms", "o"];
  X = "x";
  Y = "y";
  XY = "xy";
  LEFT = "left";
  RIGHT = "right";
  UP = "up";
  DOWN = "down";
  noop = function() {};

  /*
   * 设置元素的CSS位移
   * ele 原生的DOM元素
   */
  setTranslate = function(ele, x, y, z) {
    var cssPrefix, name, prefix, _i, _len, _results;
    cssPrefix = CSS_PREFIX_MAP.concat([]);
    cssPrefix.push("");
    _results = [];
    for (_i = 0, _len = cssPrefix.length; _i < _len; _i++) {
      prefix = cssPrefix[_i];
      name = prefix ? "" + prefix + "Transform" : "transform";
      _results.push(ele.style[name] = "translate3d(" + (x || 0) + "px, " + (y || 0) + "px, " + (z || 0) + "px)");
    }
    return _results;
  };
  Slip = (function() {
    var getCoordinates;

    getCoordinates = function(event) {
      var e, touches;
      touches = event.touches && (event.touches.length ? event.touches : [event]);
      e = (event.changedTouches && event.changedTouches[0]) || (event.originalEvent && event.originalEvent.changedTouches && event.originalEvent.changedTouches[0]) || touches[0].originalEvent || touches[0];
      return {
        "x": e.clientX,
        "y": e.clientY
      };
    };

    function Slip(ele, direction) {
      this.ele = ele;
      this.direction = direction;
      this.onStart = this.onMove = this.onEnd = noop;
      this.coord = this.eventCoords = this.cacheCoords = this.finger = this.absFinger = null;
      this.orient = [];
    }

    Slip.prototype.start = function(fn) {
      return (this.onStart = fn) && this;
    };

    Slip.prototype.move = function(fn) {
      return (this.onMove = fn) && this;
    };

    Slip.prototype.end = function(fn) {
      return (this.onEnd = fn) && this;
    };

    Slip.prototype.setCoord = function(userCoords) {
      var attr, coords, ele;
      coords = this.coord = {
        "x": userCoords[X] || 0,
        "y": userCoords[Y] || 0
      };
      ele = this.ele;
      setTranslate(ele, coords[X], coords[Y]);
      for (attr in coords) {
        ele.setAttribute(attr, coords[attr]);
      }
      return this;
    };

    Slip.prototype.onTouchStart = function(event) {
      var ret;
      this.eventCoords = getCoordinates(event);
      this.cacheCoords = this.coord;
      this.finger = this.absFinger = null;
      return ret = this.onStart.apply(this, [event]);
    };

    Slip.prototype.onTouchMove = function(event) {
      var absFinger, attr, direction, ele, eleMove, finger, moveCoords, oppDirection, orient, ret, _results;
      event.preventDefault();
      moveCoords = getCoordinates(event);
      direction = this.direction;
      finger = this.finger = {
        x: moveCoords.x - this.eventCoords.x,
        y: moveCoords.y - this.eventCoords.y
      };
      absFinger = this.absFinger = {
        x: Math.abs(finger.x),
        y: Math.abs(finger.y)
      };
      if (direction !== XY) {
        oppDirection = direction === X ? Y : X;
        if (absFinger[direction] < MIN_ALLOW_DISTANCE || absFinger[oppDirection] > MAX_OPP_ALLOW_DISTANCE) {
          return false;
        }
      }
      orient = [];
      if (absFinger.x > MIN_ALLOW_DISTANCE) {
        orient.push(finger.x < 0 ? LEFT : RIGHT);
      }
      if (absFinger.y > MIN_ALLOW_DISTANCE) {
        orient.push(finger.y < 0 ? UP : DOWN);
      }
      this.orient = orient;
      ret = this.onMove.apply(this, [event]);
      if (ret === false) {
        return false;
      }
      ele = this.ele;
      eleMove = this.coord = {
        "x": direction.indexOf(X) < 0 ? this.cacheCoords[X] : this.cacheCoords[X] - 0 + finger.x,
        "y": direction.indexOf(Y) < 0 ? this.cacheCoords[Y] : this.cacheCoords[Y] - 0 + finger.y
      };
      setTranslate(ele, eleMove[X], eleMove[Y]);
      _results = [];
      for (attr in eleMove) {
        _results.push(ele.setAttribute(attr, eleMove[attr]));
      }
      return _results;
    };

    Slip.prototype.onTouchEnd = function(event) {
      var ele, ret;
      ele = this.ele;
      return ret = this.onEnd.apply(this, [event]);
    };

    Slip.prototype.init = function() {
      var attr, direction, ele, initMove, onTouchEnd, onTouchMove, onTouchStart;
      this.coord = {
        "x": 0,
        "y": 0
      };
      onTouchStart = this._onTouchStart = (function(_this) {
        return function(event) {
          return _this.onTouchStart(event);
        };
      })(this);
      onTouchMove = this._onTouchMove = (function(_this) {
        return function(event) {
          return _this.onTouchMove(event);
        };
      })(this);
      onTouchEnd = this._onTouchEnd = (function(_this) {
        return function(event) {
          return _this.onTouchEnd(event);
        };
      })(this);
      ele = this.ele;
      ele.addEventListener("touchstart", onTouchStart, false);
      ele.addEventListener("touchmove", onTouchMove, false);
      ele.addEventListener("touchend", onTouchEnd, false);
      initMove = this.coord = {
        "x": 0,
        "y": 0
      };
      direction = this.direction;
      setTranslate(ele, initMove[X], initMove[Y]);
      for (attr in initMove) {
        ele.setAttribute(attr, initMove[attr]);
      }
      return this;
    };

    Slip.prototype.destroy = function() {
      var ele;
      ele = this.ele;
      ele.removeEventListener("touchstart", this._onTouchStart, false);
      ele.removeEventListener("touchmove", this._onTouchMove, false);
      ele.removeEventListener("touchend", this._onTouchEnd, false);
      return this;
    };

    return Slip;

  })();
  slip = function(ele, direction) {
    var instance;
    instance = new Slip(ele, direction || X);
    return instance.init();
  };
  return win.Slip = slip;
})(window, document);
