// Generated by CoffeeScript 1.7.1

/* ! CopyRight: binnng http://github.com/binnng/slip.js, Licensed under: MIT */
(function(WIN, DOC) {
  var CSS_PREFIX_MAP, DOWN, END_EVENT, IsTouch, LEFT, MAX_OPP_ALLOW_DISTANCE, MIN_ALLOW_DISTANCE, MOVE_EVENT, NULL, NUMBER_REG, RIGHT, START_EVENT, Slip, UNDEFINED, UP, WINDOW_HEIGHT, WINDOW_WIDTH, X, XY, Y, getTranslate, noop, setTransition, setTranslate, slip;
  UNDEFINED = void 0;
  NULL = null;
  MIN_ALLOW_DISTANCE = 10;
  MAX_OPP_ALLOW_DISTANCE = 40;
  CSS_PREFIX_MAP = ["webkit", "moz", "ms", "o", ""];
  NUMBER_REG = /\-?[0-9]+\.?[0-9]*/g;
  X = "x";
  Y = "y";
  XY = "xy";
  LEFT = "left";
  RIGHT = "right";
  UP = "up";
  DOWN = "down";
  IsTouch = 'ontouchend' in WIN;
  START_EVENT = IsTouch ? 'touchstart' : 'mousedown';
  MOVE_EVENT = IsTouch ? 'touchmove' : 'mousemove';
  END_EVENT = IsTouch ? 'touchend' : 'mouseup';
  WINDOW_HEIGHT = WIN['innerHeight'];
  WINDOW_WIDTH = WIN['innerWidth'];
  noop = function() {};
  setTransition = function(ele, css) {
    var name, prefix, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = CSS_PREFIX_MAP.length; _i < _len; _i++) {
      prefix = CSS_PREFIX_MAP[_i];
      name = prefix ? "" + prefix + "Transition" : "transition";
      _results.push(ele.style[name] = css);
    }
    return _results;
  };

  /*
   * 设置元素的CSS位移
   * ele 原生的DOM元素
   */
  setTranslate = function(ele, x, y, z) {
    var name, prefix, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = CSS_PREFIX_MAP.length; _i < _len; _i++) {
      prefix = CSS_PREFIX_MAP[_i];
      name = prefix ? "" + prefix + "Transform" : "transform";
      _results.push(ele.style[name] = "translate3d(" + (x || 0) + "px, " + (y || 0) + "px, " + (z || 0) + "px)");
    }
    return _results;
  };
  getTranslate = function(ele) {
    var coord, css, name, prefix, translate, _i, _len;
    translate = [];
    css = '';
    coord = '';
    for (_i = 0, _len = CSS_PREFIX_MAP.length; _i < _len; _i++) {
      prefix = CSS_PREFIX_MAP[_i];
      name = prefix ? "" + prefix + "Transform" : "transform";
      css = ele.style[name];
      if (css && typeof css === 'string') {
        coord = css.match(/\((.*)\)/g)[0];
        translate = coord && coord.match(NUMBER_REG);
        break;
      }
    }
    if (translate.length) {
      return {
        x: translate[0] || 0,
        y: translate[1] || 0,
        z: translate[2] || 0
      };
    }
  };
  Slip = (function() {
    var getCoordinates;

    getCoordinates = function(event) {
      var e, touches;
      touches = event.touches && (event.touches.length ? event.touches : [event]);
      e = (event.changedTouches && event.changedTouches[0]) || (event.originalEvent && event.originalEvent.changedTouches && event.originalEvent.changedTouches[0]) || touches[0].originalEvent || touches[0];
      return {
        "x": e.clientX,
        "y": e.clientY
      };
    };

    function Slip(ele, direction) {
      this.ele = ele;
      this.direction = direction;
      this.onStart = this.onMove = this.onEnd = noop;
      this.coord = this.eventCoords = this.cacheCoords = this.finger = this.absFinger = NULL;
      this.orient = [];
      this.isWebapp = false;
    }

    Slip.prototype.start = function(fn) {
      return (this.onStart = fn) && this;
    };

    Slip.prototype.move = function(fn) {
      return (this.onMove = fn) && this;
    };

    Slip.prototype.end = function(fn) {
      return (this.onEnd = fn) && this;
    };

    Slip.prototype.setCoord = function(userCoords) {
      var attr, coords, ele;
      coords = this.coord = {
        "x": userCoords[X] || 0,
        "y": userCoords[Y] || 0
      };
      ele = this.ele;
      setTranslate(ele, coords[X], coords[Y]);
      for (attr in coords) {
        ele.setAttribute(attr, coords[attr]);
      }
      return this;
    };

    Slip.prototype.onTouchStart = function(event) {
      var ret;
      this.eventCoords = getCoordinates(event);
      this.cacheCoords = this.coord;
      this.finger = this.absFinger = NULL;
      if (this.isWebapp) {
        this.onWepappStart(event);
      }
      return ret = this.onStart.apply(this, [event]);
    };

    Slip.prototype.onTouchMove = function(event) {
      var absFinger, attr, direction, ele, eleMove, finger, moveCoords, oppDirection, orient, ret, _results;
      event.preventDefault();
      moveCoords = getCoordinates(event);
      direction = this.direction;
      finger = this.finger = {
        x: moveCoords.x - this.eventCoords.x,
        y: moveCoords.y - this.eventCoords.y
      };
      absFinger = this.absFinger = {
        x: Math.abs(finger.x),
        y: Math.abs(finger.y)
      };
      if (direction !== XY) {
        oppDirection = direction === X ? Y : X;
        if (absFinger[direction] < MIN_ALLOW_DISTANCE || absFinger[oppDirection] > MAX_OPP_ALLOW_DISTANCE) {
          return false;
        }
      }
      orient = [];
      if (absFinger.x > MIN_ALLOW_DISTANCE) {
        orient.push(finger.x < 0 ? LEFT : RIGHT);
      }
      if (absFinger.y > MIN_ALLOW_DISTANCE) {
        orient.push(finger.y < 0 ? UP : DOWN);
      }
      this.orient = orient;
      ret = this.onMove.apply(this, [event]);
      if (ret === false) {
        return false;
      }
      ele = this.ele;
      eleMove = this.coord = {
        "x": direction.indexOf(X) < 0 ? this.cacheCoords[X] : this.cacheCoords[X] - 0 + finger.x,
        "y": direction.indexOf(Y) < 0 ? this.cacheCoords[Y] : this.cacheCoords[Y] - 0 + finger.y
      };
      setTranslate(ele, eleMove[X], eleMove[Y]);
      _results = [];
      for (attr in eleMove) {
        _results.push(ele.setAttribute(attr, eleMove[attr]));
      }
      return _results;
    };

    Slip.prototype.onTouchEnd = function(event) {
      var ele, ret, trans;
      ele = this.ele;
      if (this.isWebapp) {
        this.onWepappEnd(event);
      }
      ret = this.onEnd.apply(this, [event]);
      trans = getTranslate(this.ele);
      if (trans) {
        return this.setCoord(trans);
      }
    };

    Slip.prototype.onWepappStart = function(event) {
      return setTransition(this.ele, NULL);
    };

    Slip.prototype.onWepappEnd = function(event) {
      var css, ele, isDown, isLeft, isRight, isUp, isValidGesture, isVerticalWebapp, orient, page, pageNum, trans;
      orient = this.orient.join("");
      css = "";
      trans = 0;
      page = this.page;
      pageNum = this.pageNum;
      ele = this.ele;
      isUp = orient.indexOf(UP) > -1;
      isDown = orient.indexOf(DOWN) > -1;
      isLeft = orient.indexOf(LEFT) > -1;
      isRight = orient.indexOf(RIGHT) > -1;
      isVerticalWebapp = this.direction === Y;
      isValidGesture = (isVerticalWebapp && (isUp || isDown)) || (!isVerticalWebapp && (isLeft || isRight));
      if (isValidGesture) {
        if (isUp || isLeft) {
          page++;
        }
        if (isDown || isRight) {
          page--;
        }
        if (page === pageNum) {
          page = pageNum - 1;
        }
        if (page === -1) {
          page = 0;
        }
        setTransition(ele, "all .4s ease-in");
        if (isVerticalWebapp) {
          trans = "-" + (page * WINDOW_HEIGHT);
          setTranslate(ele, 0, trans, 0);
        } else {
          trans = "-" + (page * WINDOW_WIDTH);
          setTranslate(ele, trans, 0, 0);
        }
        return this.page = page;
      }
    };

    Slip.prototype.init = function() {
      var attr, direction, ele, initMove, onTouchEnd, onTouchMove, onTouchStart;
      this.coord = {
        "x": 0,
        "y": 0
      };
      onTouchStart = this._onTouchStart = (function(_this) {
        return function(event) {
          return _this.onTouchStart(event);
        };
      })(this);
      onTouchMove = this._onTouchMove = (function(_this) {
        return function(event) {
          return _this.onTouchMove(event);
        };
      })(this);
      onTouchEnd = this._onTouchEnd = (function(_this) {
        return function(event) {
          return _this.onTouchEnd(event);
        };
      })(this);
      ele = this.ele;
      ele.addEventListener(START_EVENT, onTouchStart, false);
      ele.addEventListener(MOVE_EVENT, onTouchMove, false);
      ele.addEventListener(END_EVENT, onTouchEnd, false);
      initMove = this.coord = {
        "x": 0,
        "y": 0
      };
      direction = this.direction;
      setTranslate(ele, initMove[X], initMove[Y]);
      for (attr in initMove) {
        ele.setAttribute(attr, initMove[attr]);
      }
      return this;
    };

    Slip.prototype.destroy = function() {
      var ele;
      ele = this.ele;
      ele.removeEventListener(START_EVENT, this._onTouchStart, false);
      ele.removeEventListener(MOVE_EVENT, this._onTouchMove, false);
      ele.removeEventListener(END_EVENT, this._onTouchEnd, false);
      return this;
    };

    Slip.prototype.webapp = function(elPages) {
      var elPage, elPagesLen, ele, pageNum, _i, _j, _len, _len1;
      ele = this.ele;
      if (typeof elPages === "string") {
        elPages = ele.querySelectorAll(elPages);
      } else {
        elPages = elPages || ele.childNodes;
      }
      this.isWebapp = true;
      this.page = 0;
      this.elPages = elPages;
      elPagesLen = elPages.length;
      pageNum = this.pageNum = elPagesLen ? elPagesLen : 0;
      if (pageNum > 0) {
        ele.style.height = "" + (WINDOW_HEIGHT * pageNum) + "px";
        for (_i = 0, _len = elPages.length; _i < _len; _i++) {
          elPage = elPages[_i];
          elPage.style.height = "" + WINDOW_HEIGHT + "px";
        }
        if (this.direction === X) {
          ele.style.width = "" + (WINDOW_WIDTH * pageNum) + "px";
          for (_j = 0, _len1 = elPages.length; _j < _len1; _j++) {
            elPage = elPages[_j];
            elPage.style.width = "" + WINDOW_WIDTH + "px";
            elPage.style.cssFloat = LEFT;
          }
        }
      }
      this.fullscreen();
      return this;
    };

    Slip.prototype.fullscreen = function() {
      var child, ele, parent;
      if (this.isWebapp) {
        ele = this.ele;
        child = ele;
        while (parent = child.parentNode) {
          if (parent.nodeType === 1) {
            parent.style.height = "100%";
            parent.style.overflow = "hidden";
          }
          child = parent;
        }
      }
      return this;
    };

    return Slip;

  })();
  slip = function(ele, direction) {
    var instance;
    instance = new Slip(ele, direction || X);
    return instance.init();
  };
  return WIN.Slip = slip;
})(window, document);
